apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-master
spec:
 replicas: 1
 selector:
   matchLabels:
     app: redis_master_app
     type: backend
 template:
   metadata:
     name: redis-master-pod
     labels:
      app: redis_master_app
      type: backend
   spec:
    containers:
      - image: redis
        name: master-redis-devops
        resources:
         requests:
           memory: "100Mi"
           cpu: "100m"
        ports:
          - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
 name: redis-master
spec:
 type: ClusterIP
 ports:
   - port: 6379
     targetPort: 6379
 selector:
   app: redis_master_app